version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: konstantinpanchik/docker-project-74:latest
    command: make dev
  test:
    build:
      context: .
      dockerfile: Dockerfile.production
    command: make test
    depends_on:
      - app
